### ISSUE TITLE
Add a project form shows blank page when user is not logged in

### ISSUE THREAD

**Issue by glaroc** [PEM-Humboldt/projects-se-ui#106]

**Comment by Angrypixels** [comment]
Redirect to sing in page should be implemented, agreed.

**Comment by erikasv** [comment]
@jmlord I think this would be better handled as a redirect if there is no user logged directly from the php page itself

**Comment by jmlord** [comment]
Hi, Kaitlyn has implemented the functionality in members website. It will come in BON in a Box soon.

**Comment by erikasv** [comment]
Great
