### ISSUE TITLE
Generar las funcionalidades especiales para el formulario de creación de proyecto

### ISSUE THREAD

**Issue by ManuelStardust** [PEM-Humboldt/projects-se-ui#25]
# Descripción y resultado 

Programar los casos especiales para lograr la funcionalidad completa del formulario como se estableció en el documento de diseño.

Un ejemplo de estos casos especiales son los campos que se deben presentar en el formulario si se está llenando un proyecto de monitoreo, o cuando se agrega más de un contacto para el proyecto o cuando el metadata provider no es un contacto del proyecto.

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/projects-se-ui/25?planning-poker) with Zenhub @ManuelStardust

**Comment by ManuelStardust** [comment]
Se actualizó la rama https://github.com/GEO-BON/bon-in-a-box-toolbox/tree/projectForm con los commits 494de2f3c794cce5e1818aafdf04d3f98ed834be y 55fce5f72ea3f1e8be750312c82ed44c12d38bde.

**Comment by ManuelStardust** [comment]
@CAScgutierrez @erikasv
