### ISSUE TITLE
Guardar en la DB la información de un nuevo proyecto

### ISSUE THREAD

**Issue by ManuelStardust** [PEM-Humboldt/projects-se-ui#26]
Almacenar la información del formulario de creación de proyectos en la DB.

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/projects-se-ui/26?planning-poker) with Zenhub @ManuelStardust

**Comment by ManuelStardust** [comment]
Se generaron las funciones para almacenar un nuevo proyecto teniendo en cuenta las anotaciones y condicioens de las descripciones de cada campo.

Es neceario hacer una prueba general de diligenciamiento de información de un proyecto para probar el flujo correcto de almacenamiento.
