### ISSUE TITLE
Mezclar rama oct-release en projectForm y projectsPage

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/projects-se-ui#32]
# Descripción y resultados

La rama `oct-release` tiene las actualizaciones realizadas desde el equipo de Canadá. Se debe mezclar en las ramas `projectForm` y `projectsPage_v2` para incluir los cambios del sitio general.

Manuel se encarga de mezclar en la rama `projectForm` (que seguramente es la que puede verse afectada) y Erika se encarga de la rama `projectsPage_v2`.

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/projects-se-ui/32?planning-poker) with Zenhub @ManuelStardust

**Comment by erikasv** [comment]
rama `projectsPage_v2` actualizada

**Comment by ManuelStardust** [comment]
rama projectForm actualizada
