### ISSUE TITLE
Implementar endpoint para likes en proyectos

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/projects-se-ui#38]
# Descripción y resultado

En la rama [likeProject](https://github.com/GEO-BON/bon-in-a-box-toolbox/compare/projectForm...likeProject) se creó el archivo y la cáscara para implementar el endpoint.

Se debe cambiar la forma de identificar el usuario, en la primera propuesta se recibe el token del usuario, pero se debe cambiar para usar la sesión activa para identificar al usuario, en caso de que no haya un usuario logueado simplemente retornar 401.

Desde el front se había hecho la implementación para enviar el token del usuario, se debe cambiar esto para hacer la petición con el `action` y el `projectId`. También se debe cambiar la lógica para que se ignore la respuesta en caso de que el endpoint de php responda 401, pero si responde algún otro error se debe mostrar un mensaje temporal diciendo que no se pudo guardar el like del proyecto. Todo lo del front está en la rama [likeProject](https://github.com/PEM-Humboldt/projects-se-ui/compare/likeProject) del front

# Consideraciones
- En cualquier caso de error (401 y otros) no se debe cambiar el estado del corazón
- Dejar la dependencia para las cookies e igual evaluar la existencia de un token, en caso de que no haya token, deshabilitar el corazón para darle like al proyecto

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/projects-se-ui/38?planning-poker) with Zenhub @ManuelStardust

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/projects-se-ui/38?planning-poker) with Zenhub @ManuelStardust

**Comment by ManuelStardust** [comment]
Se actualizaron los servicios del API para incluir la consulta de likes de un proyecto en el end point project y el almacenamiento y actualización de likes en el endpoint like_project.

Commits:
[c4450a53df43e8b9f953402ab2755ba47d8792ae](https://github.com/GEO-BON/bon-in-a-box-toolbox/commit/c4450a53df43e8b9f953402ab2755ba47d8792ae)
[7628dece863f0357ee392cad5122b8f23aa607d4](https://github.com/GEO-BON/bon-in-a-box-toolbox/commit/7628dece863f0357ee392cad5122b8f23aa607d4)

**Comment by ManuelStardust** [comment]
Se elimino el parámetro de token en la consulta al API de actualización de likes. Se dejo la funcionalidad del like para que sea visible el icono del like si existe token de sesión. Se decidio no implementar aún la visualización del mensaje de respuesta cuando no es posible actualizar el like.

Commits:
[53665a1091002328a4a6d7de8465c065ba8df186](https://github.com/PEM-Humboldt/projects-se-ui/commit/53665a1091002328a4a6d7de8465c065ba8df186)
[58e51eab554df0ef3eebd232538961f7ae2f4511](https://github.com/PEM-Humboldt/projects-se-ui/commit/58e51eab554df0ef3eebd232538961f7ae2f4511)

**Comment by erikasv** [comment]
@ManuelStardust crea los PR, esas ramas estaban esperando esta tarea para ser mezcladas
