### ISSUE TITLE
Ajustes a formulario de creación de proyecto

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/projects-se-ui#42]
# Descripción y resultado

Realizar los ajustes discutidos en la reunión del 11 de agosto. Entre los que están:

- Separación de las organizaciones que se van agregando
- Aceptar más de una organización leading
- Cambiar texto de botón `+ Add organization` a `+ Another organization`
- Cambiar texto de sección `Organization` a `Organizations`
- Cambios en agregar contacto cuando se selecciona la persona logueada
- Cambio en texto del botón para agregar contacto
- Traer la lista de organizaciones en el contacto del proyecto
- Separación de los contactos que se van agregando
- Cambiar `project continues` por `project ongoing`
- Validar que el año final sea mayor al año inicial
- Agregar mensaje al usuario en la parte geográfica para que ingrese lo que mejor represente el área de su proyecto
- Agregar botón de Cancelar a los nuevos contactos / organizaciones / data publishing site / etc
- Agregar opción de más funders
- Nota para que solo se reciban archivos pdf en los documentos
- Hacer que la imagen del proyecto sea obligatoria.
- Agregar galería de imágenes para seleccionar una en caso de que el usuario no quiera subir una
- Agregar la lista de licencias para escoger (entre las creative commons)
- Agregar funcionalidad para limpiar formulario

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/projects-se-ui/42?planning-poker) with Zenhub @ManuelStardust

**Comment by ManuelStardust** [comment]
Commits:
[9f65e089410eaa7d77dd7e90b586b3f46374319b](https://github.com/GEO-BON/bon-in-a-box-toolbox/commit/9f65e089410eaa7d77dd7e90b586b3f46374319b)
[bf0743ba46dfb6c6f96de688a3d356f20b3fcd70](https://github.com/GEO-BON/bon-in-a-box-toolbox/commit/bf0743ba46dfb6c6f96de688a3d356f20b3fcd70)
[3069477e6b08c771e20a0e17d94048b44456e87d](https://github.com/GEO-BON/bon-in-a-box-toolbox/commit/3069477e6b08c771e20a0e17d94048b44456e87d)
[4165d9f3997c7d0e07dd08c3792dc1e4a435bde3](https://github.com/GEO-BON/bon-in-a-box-toolbox/commit/4165d9f3997c7d0e07dd08c3792dc1e4a435bde3)
