### ISSUE TITLE
Actualizar consultas del API de proyectos

### ISSUE THREAD

**Issue by ManuelStardust** [PEM-Humboldt/projects-se-ui#45]
Actualizar las consultas del API de proyectos según el nuevo nombre para la tabla de oranizaciones.

**Comment by erikasv** [comment]
Favor incluir también un campo que puse en esta [rama](https://github.com/GEO-BON/bon-in-a-box-toolbox/compare/projectForm...likeProject#diff-5c1ea0ff447f6a28d763c8376253608101d694258ae99487baa685661902b6fcR174) para determinar si al usuario actual le gusta este proyecto, dejé un comentario en un TODO, podríamos usar la sesión o enviar el token del usuario, no me inclino por ninguna de las dos opciones.

**Comment by ManuelStardust** [comment]
[2016d8538668a839d6943a0b922e4d7deb2a7e83](https://github.com/GEO-BON/bon-in-a-box-toolbox/commit/2016d8538668a839d6943a0b922e4d7deb2a7e83)

**Comment by ManuelStardust** [comment]
Commits:
[347170c75c516f0192a6229f365e4d31bd189e6e](https://github.com/GEO-BON/bon-in-a-box-toolbox/commit/347170c75c516f0192a6229f365e4d31bd189e6e)
[e4844daabeb83ec28dbacaeb8bfd06987af77687](https://github.com/GEO-BON/bon-in-a-box-toolbox/commit/e4844daabeb83ec28dbacaeb8bfd06987af77687)
