### ISSUE TITLE
Implementar consulta para jsonld

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/projects-se-ui#48]
# Descripción y resultado

Implementar la consulta para generar el jsonld de un proyecto haciendo la correcta consulta a la base de datos, actualmente en la rama [jsonld](https://github.com/GEO-BON/bon-in-a-box-toolbox/compare/projectForm...jsonld) hay un mockup con los datos que debe tener el objeto resultante. 

# Consideraciones
Creo que faltan algunas propiedades, pero por ahora se puede ir implementando eso para hacer pruebas con el ambiente de azure

El endpoint acordado es: `/api/json?projectId={projectId}`

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/projects-se-ui/48?planning-poker) with Zenhub @ManuelStardust

**Comment by ManuelStardust** [comment]
Commits:
[7fa6c2429221c722c416c1a8a72a7ae843cb4eeb](https://github.com/GEO-BON/bon-in-a-box-toolbox/commit/7fa6c2429221c722c416c1a8a72a7ae843cb4eeb)

**Comment by erikasv** [comment]
@ManuelStardust haz la implementación en la rama mencionada, y revierte el commit de la rama de projectForm

**Comment by ManuelStardust** [comment]
Commits:
[a2c88b2df97849c2637954ce5648bb2b13b53213](https://github.com/GEO-BON/bon-in-a-box-toolbox/commit/a2c88b2df97849c2637954ce5648bb2b13b53213)
[3bcba1bd5903989ba29e6b98d6b5491c8afa7e10](https://github.com/GEO-BON/bon-in-a-box-toolbox/commit/3bcba1bd5903989ba29e6b98d6b5491c8afa7e10)
