### ISSUE TITLE
Cargar imágenes en la ficha del proyecto

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/projects-se-ui#50]
# Descripción y resultados

En la ficha del proyecto (y tal vez en el formulario de creación/edición) se deben mostrar las imágenes de los grupos taxonómicos, ebvs, ecositemas, etc.

Estas imágenes se pueden descargar desde el repositorio del front de react.

Adicionalmente se debe solicitar a César la lista de imágenes definitivas entre las que se podrá escoger para relacionarla al proyecto. De esta forma el proyecto siempre tendrá imagen y no necesitara una aleatoria desde la aplicación de react.

TAREA:
Al asignar la imagen del proyecto, crear una tarea para le aplicación de react en la que se elimine la lógica para usar una imagen aleatoria y se eliminen las imágenes del repositorio

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/projects-se-ui/50?planning-poker) with Zenhub @ManuelStardust

**Comment by ManuelStardust** [comment]
Se cargaron las imagenes para visulización de Ebvs, grupos biologicos y ecosistemas. Adicionalmente se actualizaron las imagenes precargadas para los proyectos. 

Esta pendiente asignar una imagen precargada a los proyectos existentes sin imagen una vez se nos entregue el dump de la base de datos actualizada.

Commits: 

[a79c604454c6ce80fb6777a4d1898cf60ad3900b](https://github.com/GEO-BON/bon-in-a-box-toolbox/commit/a79c604454c6ce80fb6777a4d1898cf60ad3900b)
[6f7f09a624bbb387e4d7530fc88900de503efadd](https://github.com/GEO-BON/bon-in-a-box-toolbox/commit/6f7f09a624bbb387e4d7530fc88900de503efadd)
[44e3409ca386b0f7d56ebc6b359f9d95d9c608d4](https://github.com/GEO-BON/bon-in-a-box-toolbox/commit/44e3409ca386b0f7d56ebc6b359f9d95d9c608d4)
[2da15e3557e873218f0514f22df4d7122ab02aca](https://github.com/GEO-BON/bon-in-a-box-toolbox/commit/2da15e3557e873218f0514f22df4d7122ab02aca)
[96cc6f3c14b4135d4e435a5b3e3a40e4c693b581](https://github.com/GEO-BON/bon-in-a-box-toolbox/commit/96cc6f3c14b4135d4e435a5b3e3a40e4c693b581)
[c610210f50ff306701f3e3d72fe93aa9711ab0ba](https://github.com/GEO-BON/bon-in-a-box-toolbox/commit/c610210f50ff306701f3e3d72fe93aa9711ab0ba)
