### ISSUE TITLE
Ajustes en páginas del api

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/projects-se-ui#51]
# Descripción y resultado

Realizar los siguientes ajustes en los endpoints (`/api/project` y  `/api/json`):
- [x] Cuando se accede a las páginas del api (o se hacen peticiones a estos endpoints) sin los parámetros GET indicados (`handler` o `projectId` según sea el caso) se están mostrando warnings y errores de php. Agregar las verificaciones necesarias para controlar estos errores y retornar mensajes adecuados.
- [x] Cambiar las consultas de las personas, para no traer el campo `name` de la base de datos, sino los campos `firstname` y `lastname`, pero se deben concatenar para que el api siga retornando el campo `name`

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/projects-se-ui/51?planning-poker) with Zenhub @ManuelStardust

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/projects-se-ui/51?planning-poker) with Zenhub @ManuelStardust

**Comment by ManuelStardust** [comment]
Se actualizó la comprobación de parametros de entrada a los endpoints.
Se realizó el cambio de campos de consulta para los nombres de personas.

Commits: 

[615f91a8ae32ff8f5db25796e32a960e8dffe96b](https://github.com/GEO-BON/bon-in-a-box-toolbox/pull/54/commits/615f91a8ae32ff8f5db25796e32a960e8dffe96b)
[6f07ff3321610bc302468390d7241509a46e15d5](https://github.com/GEO-BON/bon-in-a-box-toolbox/pull/54/commits/6f07ff3321610bc302468390d7241509a46e15d5)
