### ISSUE TITLE
Eliminar la imagen aleatoria para la visualización del proyecto

### ISSUE THREAD

**Issue by ManuelStardust** [PEM-Humboldt/projects-se-ui#56]
# Descripción y resultado
Eliminar la lógica para usar una imagen aleatoria en el front y eliminar las imágenes y la función del repositorio.

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/projects-se-ui/56?planning-poker) with Zenhub @ManuelStardust
