### ISSUE TITLE
Ajustes a página de proyecto

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/projects-se-ui#64]
# Descripción y resultado

- [x] Cambiar parámetro del api a `handle`
- [x] Agregar sección de licencia
- [x] Sacar el hostname de `window.location.hostname` y quitar la otra variable de ambiente
- [x] Mostrar mensaje cuando se copió la url del sitio

**Comment by ManuelStardust** [comment]
La seccción de licencia ya se encontraba implementada.
