### ISSUE TITLE
Ajutes en el sitio de php

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/projects-se-ui#66]
- [x] Cambiar el parámetro del api del proyecto a `handle`
- [x] https://github.com/GEO-BON/bon-in-a-box-toolbox/pull/60#discussion_r1324959680
- [x] https://github.com/GEO-BON/bon-in-a-box-toolbox/pull/60#discussion_r1325014121
- [x] https://github.com/GEO-BON/bon-in-a-box-toolbox/pull/60#discussion_r1325016750
- [x] Validar handle: https://github.com/GEO-BON/bon-in-a-box-toolbox/pull/60/files/e720b7dbcfc807ea09c15c8eb1b71e4b52a736b4#r1325018551 (lo del espacio discutirlo con César y Diego)
- [x] https://github.com/GEO-BON/bon-in-a-box-toolbox/pull/60#discussion_r1325020166
- [x] https://github.com/GEO-BON/bon-in-a-box-toolbox/pull/60#discussion_r1325029917
- [x] https://github.com/GEO-BON/bon-in-a-box-toolbox/pull/60#discussion_r1325034044
- [x] https://github.com/GEO-BON/bon-in-a-box-toolbox/pull/60#discussion_r1325039521
- [x] https://github.com/GEO-BON/bon-in-a-box-toolbox/pull/60#discussion_r1325046338
- [x] https://github.com/GEO-BON/bon-in-a-box-toolbox/pull/60#discussion_r1325015559
- [x] https://github.com/GEO-BON/bon-in-a-box-toolbox/pull/60#discussion_r1325024883
- [x] Breadcrumbs: https://github.com/GEO-BON/bon-in-a-box-toolbox/pull/60#discussion_r1325043801 https://github.com/GEO-BON/bon-in-a-box-toolbox/pull/60#discussion_r1324956497
- [x] https://github.com/GEO-BON/bon-in-a-box-toolbox/pull/60#discussion_r1324948951
- [x] Actualizar valor de `aggregateRating` en el jsonld para que cuente los likes del proyecto

**Comment by ManuelStardust** [comment]
Commits
[dc36ea4895968a2a44d6645b1c8220e5ec45f769](https://github.com/GEO-BON/bon-in-a-box-toolbox/pull/60/commits/dc36ea4895968a2a44d6645b1c8220e5ec45f769)
[dcda57ed70cc4c575f0c80ff25d8a6c8477e9f4c](https://github.com/GEO-BON/bon-in-a-box-toolbox/pull/60/commits/dcda57ed70cc4c575f0c80ff25d8a6c8477e9f4c)
[9d3bf0f671cbabfcf43225e06284b6b58da98f6e](https://github.com/GEO-BON/bon-in-a-box-toolbox/pull/60/commits/9d3bf0f671cbabfcf43225e06284b6b58da98f6e)
[13d3e80610bb14311f853eb591ed5a4bfcf6ca5d](https://github.com/GEO-BON/bon-in-a-box-toolbox/pull/60/commits/13d3e80610bb14311f853eb591ed5a4bfcf6ca5d)
[498a12773eeb506cb67e28f4a6bf2d28f07dd60e](https://github.com/GEO-BON/bon-in-a-box-toolbox/pull/60/commits/498a12773eeb506cb67e28f4a6bf2d28f07dd60e)
