### ISSUE TITLE
Review: search UI styling

### ISSUE THREAD

**Issue by jmlord** [PEM-Humboldt/projects-se-ui#67]
1) Search results are mostly outside of screen. We can only see the first row. Solutions could be to put projects, map and sort on a sidebar, to move or remove the BON in a Box logo that takes vertical space, or to collapse the search area (like google have the searchbar centered before first search, and after it's small and on top).

2) Ongoing and closed should be a label for the radio button. The for= attribute is missing.

3) Countries and biologic group dropdowns look like text fields. It should have dropdown styling with  downwards arrow.

4) Weird alignment of tags and results:
![image](https://github.com/PEM-Humboldt/projects-se-ui/assets/6223744/825a7e2b-4221-4896-9494-434a9dac9a7e)

5) I suggest a padding between horizontal line and search results:
![image](https://github.com/PEM-Humboldt/projects-se-ui/assets/6223744/46659fbb-28bf-4d99-b373-a913736feffb)

**Comment by jmlord** [comment]
> Number 2. The label and input are created by the react-bootstrap component [Form.Check](https://react-bootstrap.netlify.app/docs/forms/checks-radios/) and can't control the `for` property

Can you control htmlFor?
(They renamed it for react, see https://stackoverflow.com/a/22752418/3519951)

**Comment by erikasv** [comment]
That prop is not for the element being used, but it's already solved.
