### ISSUE TITLE
Review: search UI functionnality

### ISSUE THREAD

**Issue by jmlord** [PEM-Humboldt/projects-se-ui#68]
1) Pressing Enter anywhere in the search form should perform the search. Currently we have to click the magnifier button.

2) UI crashed when I set the country or the biologic group
`Uncaught ReferenceError: setCountries is not defined`

3) Translation in a search engine is uncommon. A tooltip when we hover the button could help understand (but that would not work in mobile...). How about a bubble that would appear somewhere near the button when we click on it? Something like "Translation to English activated" or "Results will be in their original language"...

4) Most viewed, Least viewed, Latest does not seem to make a difference. If intended, it should be hidden until functional, to avoid confusion.

**Comment by MathuC** [comment]
5. Start date-End date not working. (Eg: Search query: "marine"; Start date: 2021-01-01; End date: 2023-01-01)

6. "Monitoring of marine ecosystems of Portete Bay" result is present 4 times when the search query is "marine". Furthermore, when you click on the "+" button, all 4 cards open up.

**Comment by erikasv** [comment]
About point 3, we can't imagine what you say about the bubble, but we are thinking something to explain the functionality. The rest of the points are solved since these were happening because the search page is not finished
