### ISSUE TITLE
Project page

### ISSUE THREAD

**Issue by MathuC** [PEM-Humboldt/projects-se-ui#69]
Projects that have a project page don't open up when the link is clicked (right arrow button). The only project that it works for is "Title of the project 1". 
There's the folder "frontend" missing in the link. The link shouldn't be e.g.: "https://boninabox.geobon.org/projects/3", it should be e.g.: "https://boninabox.geobon.org/frontend/projects/3".

**Comment by erikasv** [comment]
@ManuelStardust esto se está generando al momento de la indexación, porfa revisar y ajustar.

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/projects-se-ui/69?planning-poker) with Zenhub @ManuelStardust

**Comment by ManuelStardust** [comment]
> Projects that have a project page don't open up when the link is clicked (right arrow button). The only project that it works for is "Title of the project 1". There's the folder "frontend" missing in the link. The link shouldn't be e.g.: "https://boninabox.geobon.org/projects/3", it should be e.g.: "https://boninabox.geobon.org/frontend/projects/3".

This happens because the first projects had test data, however the current code generates the correct URL and it will be updated when the projects are indexed again.
