### ISSUE TITLE
Conectar mapa con resultados de tarjeras pequeñas

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/projects-se-ui#78]
# Descripción

Conectar el mapa que dejó César en la rama [mapLeaflet](https://github.com/PEM-Humboldt/projects-se-ui/tree/mapLeaflet) con los resultados de la búsqueda.

La idea es que en el tooltip aparezca el nombre del proyecto y es un enlace a la página del proyecto.

El punto ya viene en la consulta desde el middleware.

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/projects-se-ui/78?planning-poker) with Zenhub @ManuelStardust

**Comment by ManuelStardust** [comment]
Se dejo funcionando el mapa con los resultados de la consulta de poryectos. Como actualmente los proyectos aún no cuentan con valores en la coordenadas se generaron datos de prueba en el middleware: [testPoints](https://github.com/PEM-Humboldt/biab-projects-middleware/tree/testPoints)
