### ISSUE TITLE
Sanitizar comillas en formulario

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/projects-se-ui#81]
# Descripción y resultado

Ver discusión en slack.

La idea es cambiar todas las comillas dobles (`"`, `“` Y `”`) por comillas simples (`'`) antes de guardar los proyectos en la base de datos. Esto porque las comillas dobles generan problemas al indexar.

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/projects-se-ui/81?planning-poker) with Zenhub @ManuelStardust

**Comment by ManuelStardust** [comment]
pattern: /^[a-zA-ZÀ-ÿ0-9\/@'.,;:_-\s]+$/

Commits:
[8ceaf5e7a71fca399da3ef4c09471b48b9ebeda1](https://github.com/GEO-BON/bon-in-a-box/commit/8ceaf5e7a71fca399da3ef4c09471b48b9ebeda1)
