### ISSUE TITLE
Project time span unknown

### ISSUE THREAD

**Issue by jmlord** [PEM-Humboldt/projects-se-ui#95]
Project closing date sometimes displays as unkown, but the word unknown is just there in bold with no explanation:

![image](https://github.com/GEO-BON/bon-in-a-box/assets/6223744/efab2637-357a-435a-a442-8ea8c5c20d18)

We should have something like "Time span: unknown" or just remove it when unknown.

**Comment by erikasv** [comment]
That's actually the project status, the dates are already hidden when unknown. For this we could add a title or a tooltip. We'll define with Cesar.

**Comment by Angrypixels** [comment]
a tooltip should work letting them now that the status of the project is unknown at the moment

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/projects-se-ui/95?planning-poker) with Zenhub @erikasv @ManuelStardust
