### ISSUE TITLE
Liking a project should be available from the search UI

### ISSUE THREAD

**Issue by jmlord** [PEM-Humboldt/projects-se-ui#98]
When unfolding the project card, we see the number of likes and a heart icon. It is really tempting to click the heart icon there.

However, it is not clickable.

Expectation is that it would be clickable and do the same as clicking the heart in the project page.

**Comment by Angrypixels** [comment]
The results come from the indexer so is not quite easy to implement. I would say we can change it a little with text next to it to let them know is how many people like the project, and change it so it doesn't have a hover behaviour

**Comment by jmlord** [comment]
If we are able to show the heart it is because we know it's a project from our DB. And we also should know it's ID? If yes an API call could add a like to it...

The hard thing would be to like projects that are not in our DB...

**Comment by erikasv** [comment]
We decided to avoid api call to get information from our database to be able to integrate new sources in the future. To like a project in the results page would mean to query results from the indexer to know if the current user already liked them, so we decided against it
