### ISSUE TITLE
Project card pictures load slowly

### ISSUE THREAD

**Issue by jmlord** [PEM-Humboldt/projects-se-ui#99]
When unfolding a project card, the image loads very slowly since it has a high resolution.

When uploading the project images, we should create a thumbnail version that fits our project card and would be much quicker to load.

**Comment by erikasv** [comment]
This must be in bon-in-a-box repo. It needs to be handled when uploading the image in the project creation/edition and when generating the jsonld in the api

**Comment by jmlord** [comment]
Ok thanks, it's not always easy to know in which repo to put the issue!
